-- AlterTable
ALTER TABLE "Business" ADD COLUMN     "avgRating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalRating" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalReview" INTEGER NOT NULL DEFAULT 0;
